language: go
go_import_path: github.com/evrynet-official/evrynet-client
sudo: false
env:
  global:
    - GO111MODULE=on
services:
  - docker
jobs:
  include:
    # This builder only tests code linters on latest version of Go
    - stage: build
      os: linux
      dist: xenial
      go: 1.11.x
      env:
        - GOLANGCI_LINT_VERSION=1.15.0
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ${TRAVIS_HOME}/bin v${GOLANGCI_LINT_VERSION}
        - ./vendor.sh
        - go run build/ci.go lint

    - stage: build
      os: linux
      dist: xenial
      go: 1.11.x
      script:
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES

    - stage: build
      os: linux
      dist: xenial
      go: 1.12.x
      script:
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES

    # These are the latest Go versions.
    - stage: build
      os: linux
      dist: xenial
      go: 1.13.x
      script:
        - go mod vendor
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES

after_success:
  - docker --version
  - docker build . -f ./dev/onenode/Dockerfile --label "commit=$TRAVIS_COMMIT" -t $TRAVIS_COMMIT
  - docker run -d -it $TRAVIS_COMMIT