version: "3"
services:
  geth-grafana:
    image: grafana/grafana
    container_name: geth-grafana
    restart: always
    ports:
      - 3001:3000
    networks:
      chainnet:
        ipv4_address: 172.25.0.169
    volumes:
      - /var/lib/docker/volumes/grafana-volume/_data:/var/lib/grafana

  geth-influxdb:
    image: influxdb
    container_name: geth-influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=geth
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=test
      - INFLUXDB_USER_PASSWORD=test
    networks:
      chainnet:
        ipv4_address: 172.25.0.196
    volumes:
      - /var/lib/docker/volumes/influxdb-volume/_data:/var/lib/influxdb

